sudo: false

language: node_js

node_js:
  - "4"
  - "6"

script:
  - npm run build:prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  name: DeployBot
  on:
    tags: true
    node_js: "6"
