sudo: false

language: node_js

node_js:
  - "4"
  - "6"

script:
  - npm run build:prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: rv3AhPBCR9th2EmqzwZV6aXq6NEJehYVcyNnGqTRHnzc7dSkXK5CFGPwFsoNImT4ojkCavFT2g+Mr/TwOBCSMTynq8mdZNj/45izPZ2kKd8wn8QsgpUnU1OYdQDSBV6NBWY4Hbj5Bi1G857EFtx67gxHnZTidglCsZ2MT1VCssp+vGl6Up23cC1M2U6GIwaMeU9xUlcNHOJXeI+jNDWHkQ37kLLyiRPOlYfstHHKXsvniyPuwNdr7g37KMAICJ4ULCp5i1QQTYEA20dZcZgJfdhxD5sOgnPcbJCJyXmJV/9inCWinTI2r9owzexAMIvEfv6iHpVlAoqKfnofB0QJAM2+BvI4Fawaz40UaHvk/YxtGG6nYfSuv8FFBcNts372yCrVi9Hr3YWjl/kRzx3umN6fOiQ3Sto/PQzniFTyuY4JIKOFYfHlh/b9WhLfeXb38mtXbfL4Z4jquEuXhdKEHxf77DPGH2pJi/uEcCxTj2zPow1QTbSVDEwQHWMzWH++Zhbp0Wh89jgXQC6l44grOLWhZGiS21tHLz/NE41hHaV5pNN5p60+OSl4e5mmb51ZjHOyUh5AaYqYWPskCz3UprDzs3NxJgIGkqJswuzA6nO+Ui13AkY93IYwppgmlphcJlIYhenGEqfxe913FxbC5ukivDWtrSAtOIWCe/nAhy0=
  local_dir: dist
  name: DeployBot
  on:
    tags: true
    node_js: "6"
