sudo: false

language: node_js

node_js:
  - "4"
  - "6"

script:
  - npm run build:prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: o61bByMbDRLC1LrbNK+bB/0LIaeoE0Rgni4wbeJQWiRaRdbXLsfIdyn016H5uLfePHxGojdbW205XqYUe5PLapgbA5D4N3AzC+w37VlapvUKOZzxm7tAAjpzKk2gBf5uuBZBFA2xNFrGEhRqV+XeSVzYVn8toBsbDy7HcR7PD7dQX8mz76BoZ+eAf/mczF5mTDMbxkMwM2Uw76Of2u7mR6RlvH4Fy0B5qgN8C39pW4KnCJKIeZ9gA6vMzfPD+RcRjvGWyxd0GsulC7iqDx7gznpCq+NS8P+2fSLiEYwq/Rpt1pt0ZZGh1rP1qxGpbaeCP94t9Tk12IYRGmGVmLzrvcu8RsKZ08+zACMan5EoxzhHph8fEckDwpEMLkZ0MZWKF1zagCaYfE96vniVum61QJD5Ph0F5v9I6xQAujM1La0Ncp2ToUNgI7oNqd2FxdtJ8aXO6zPwrYD9cbunvYH3TSHLS/TTph1V1UtibIJMULNZiO6QjbM8uzR1+ebDebrijpi2Owu1HuA21HFNvwtko82jkm2cGl+336KpqWRHW5j18k2hrf+QUDW/yTof/nXFsc7iANea6dlQrBp+eV8xRPjTDyLnSkCGpdh2VcMmcnPJYTKg6GSIQ55d4A5wqEBtje5lSN01BgYHQyb/4fbkaoXvh2PI4dk4gK1/dfuVlBE=
  local_dir: dist
  name: DeployBot
  on:
    tags: true
    node_js: "6"
